version: '3.7'
services:
  gitlab:
    # use second docker-compose to add image
    build:
      context: .
      dockerfile: Dockerfile
    image: "${APP_IMAGE_NAME}:${REPO_VERSION}"
    container_name: "${APP_IMAGE_NAME}"
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 8080:80

volumes:
  dbdata:
